---

################################################################
## API Gateway provisioning
################################################################

- import_playbook: ../../sagenv-common-webmethods.yaml
  vars:
    cce_provisioning_target_hostgroups: recipe2_apigateway
    cce_provisioning_template: recipe2/apigateway/template.yaml
    cce_provisioning_properties: recipe2-apigateway
    cce_provisioning_installed_product_names: apigateway
    cce_provisioning_installed_product_instance_names: apigateway
    cce_provisioning_validation_ports:
      - 5555
      - 9072
    cce_provisioning_template_params:
      - name: "repo.product"
        value: "{{ cce_provisioning_products_repo_apigateway }}"
      - name: "repo.fix"
        value: "{{ cce_provisioning_fixes_repo_apigateway }}"
      - name: "agw.key.license.alias"
        value: "*_YAIAA_10.*_*_*"
    cce_provisioning_template_params_secure:
      - name: "agw.administrator.password"
        value: "{{ cce_provisioning_agw_administrator_password }}"
  tags:
    - install
    - install-apigateway