---

## OS settings
sys_open_ports: "{{ sys_open_ports_spm }}"
limits_user: "{{ webmethods_user }}"

## default provisonning values
cce_provisioning_template_params: {}
cce_provisioning_template_params_secure: {}
cce_provisioning_installed_product_names: "notspecified"
cce_provisioning_installed_product_envs_by_name:
  LimitNOFILE: "{{ limits_openfiles }}"
  LimitNPROC: "{{ limits_processes }}"
cce_provisioning_postinstall_webmethods: true
cce_provisioning_postinstall_service_setup: true
cce_provisioning_postinstall_reboot: false
cce_provisioning_validation_ports: []
cce_provisioning_validation_ports_timeout: 900