---

## OS settings
sys_open_ports: "{{ sys_open_ports_spm }} + {{ sys_open_ports_mws }}"

limits_user: "{{ webmethods_user }}"
limits_openfiles: "250000"
limits_processes: "20000"

sysctl_config:
  vm.max_map_count: "262144"
  fs.file-max: "{{ limits_openfiles }}"