---

################################################################
## Integration Server provisioning
################################################################

- import_playbook: ../../sagenv-common-webmethods.yaml
  vars:
    cce_provisioning_target_hostgroups: recipe1_integration
    cce_provisioning_template: recipe1-apimgt-simple/integrationserver/template.yaml
    cce_provisioning_properties: recipe1-apimgt-simple-integration
    cce_provisioning_installed_product_names: integrationserver
    cce_provisioning_validation_ports:
      - 5555
      - 9999
    cce_provisioning_template_params:
      - name: "repo.product"
        value: "{{ cce_provisioning_products_repo_integrationserver }}"
      - name: "repo.fix"
        value: "{{ cce_provisioning_fixes_repo_integrationserver }}"
      - name: "is.key.license.alias"
        value: "*_PIE_10.*_*_*"
    cce_provisioning_template_params_secure:
      - name: "is.administrator.password"
        value: "{{ cce_provisioning_is_administrator_password }}"
  tags:
    - install
    - install-integrationserver