---

##some post install items for gateway  (stop local internal data store, update configs, restart gateway)
- hosts: apigateway
  tasks:
    - import_role: 
        name: command-webmethods
      vars:
        command: "stop"
        product_name: "internaldatastore"
      become: true
      become_user: "{{ webmethods_user }}"
    - import_role: 
        name: apigateway-update-configs
      vars:
        apigateway_elasticsearch_configs_toupdate:
          "pg.gateway.elasticsearch.autostart": "false"
          "pg.gateway.elasticsearch.hosts": "ip-20-35-64-225.ec2.internal:9240,ip-20-35-64-150.ec2.internal:9240,ip-20-35-64-13.ec2.internal:9240"
      become: true
      become_user: "{{ webmethods_user }}"
    - import_role: 
        name: service-webmethods
      vars:
        command: "restart"
        product_name: "apigateway"
      become: true