---

- hosts: localhost
  become: true
  tasks:
    - name: Non Root tasks
      block:
        ## this is to make sure we gather the facts again as the user {{ cce_owner }} in order to get a valid {{ ansible_env.HOME }}
        - setup:
        - import_role: 
            name: create-known-hosts
      become: false
  tags:
    - sysprep
    - setup_ansible

- hosts: "{{ inventory_groupnames }}"
  become: true
  roles:
    - role: manage-packages
    - role: update-firewall
    - role: update-os 
  tags:
    - sysprep
    - sysprep_linux