---

- hosts: all_linux:!commandcentral
  become: true
  vars:
    hostnameprefix: "sagdemo"
  tasks:
    - hostname: name={{ hostnameprefix }}-{{ "%03d" | format(ansible_default_ipv4.address.split(".")[2]|int) }}-{{ "%03d" | format(ansible_default_ipv4.address.split(".")[3]|int) }}

## temp: keep the hostname as is for cce
- hosts: commandcentral
  become: true
  tasks:
    - hostname: name=image20191120