---

################################################################
## terracotta provisioning
################################################################

- import_playbook: sagenv-common-webmethods.yaml
  vars:
    cce_provisioning_target_hostgroups: project2_apigateway
    cce_provisioning_template: project2/terracotta/template-cluster.yaml
    cce_provisioning_properties: project2-terracotta
    cce_provisioning_installed_product_names: terracotta
    cce_provisioning_validation_ports:
      - 9530
      - 9540
    cce_provisioning_template_params:
      - name: "repo.product"
        value: "{{ cce_provisioning_products_repo_terracotta }}"
      - name: "repo.fix"
        value: "{{ cce_provisioning_fixes_repo_terracotta }}"
      - name: "tc.key.license.alias"
        value: "*TerraCotta_v4_Clustering_IS_terracotta-license.key"
  tags:
    - install
    - install-terracotta