################################################################
## internal data store provisioning
################################################################

##provision
- import_playbook: sagenv-common-webmethods.yaml
  vars:
    cce_provisioning_target_hostgroups: project2_apigwinternaldatastore
    cce_provisioning_template: project2/apigwinternaldatastore/template-cluster.yaml
    cce_provisioning_properties: project2-apigwinternaldatastore
    cce_provisioning_installed_product_names: apigwinternaldatastore
    cce_provisioning_validation_ports:
      - 9240
      - 9340
    cce_provisioning_template_params:
      - name: "repo.product"
        value: "{{ cce_provisioning_products_repo_apigwinternaldatastore }}"
      - name: "repo.fix"
        value: "{{ cce_provisioning_fixes_repo_apigwinternaldatastore }}"
      - name: "fixes.apply"
        value: "[]"
  tags:
    - install
    - install-apigwinternaldatastore

##some post install items for elastic search
- hosts: project2_apigwinternaldatastore
  become: true
  become_user: "{{ webmethods_user }}"
  tasks:
    - import_role: 
        name: elasticsearch-update-seeds
      vars:
        elasticsearch_host_aliases: "{{ groups['project2_apigwinternaldatastore'] }}"
        
    ##TODO: we should be careful not to run this when product is already in use...otherwise would lose all the data
    - import_role: 
        name: elasticsearch-cleardata 
  tags:
    - install
    - install-apigwinternaldatastore
    - postinstall-apigwinternaldatastore