---

################################################################
## API Gateway provisioning
################################################################

- import_playbook: sagenv-common-webmethods.yaml
  vars:
    cce_provisioning_target_hostgroups: apigateway
    cce_provisioning_template: recipe1-apimgt-simple/apigateway/template.yaml
    cce_provisioning_properties: recipe1-apimgt-simple-apigateway
    cce_provisioning_installed_product_names: apigateway
    cce_provisioning_validation_ports:
      - 5555
      - 9072
    cce_provisioning_template_params:
      - name: "repo.product"
        value: "{{ cce_provisioning_products_repo_apigateway }}"
      - name: "repo.fix"
        value: "{{ cce_provisioning_fixes_repo_apigateway }}"
      - name: "fixes.apply"
        value: "ALL"
      - name: "agw.key.license.alias"
        value: "*_YAIAA_10.*_*_*"
    cce_provisioning_template_params_secure:
      - name: "agw.administrator.password"
        value: "{{ cce_provisioning_agw_administrator_password }}"
  tags:
    - install
    - install-apigateway

################################################################
## API Portal provisioning
################################################################

- import_playbook: sagenv-common-webmethods.yaml
  vars:
    cce_provisioning_target_hostgroups: apiportal
    cce_provisioning_template: sag-spm/template-bootstrap.yaml
    cce_provisioning_properties: spm-bootstrap
    cce_provisioning_installed_product_names: spm
    cce_provisioning_validation_ports:
      - 8092
      - 8093
  tags:
    - install
    - install-apiportal-spm

################################################################
## Integration Server provisioning
################################################################

- import_playbook: sagenv-common-webmethods.yaml
  vars:
    cce_provisioning_target_hostgroups: integration
    cce_provisioning_template: recipe1-apimgt-simple/integrationserver/template.yaml
    cce_provisioning_properties: recipe1-apimgt-simple-integration
    cce_provisioning_installed_product_names: integrationserver
    cce_provisioning_validation_ports:
      - 5555
      - 9999
    cce_provisioning_template_params:
      - name: "repo.product"
        value: "{{ cce_provisioning_products_repo_integrationserver }}"
      - name: "repo.fix"
        value: "{{ cce_provisioning_fixes_repo_integrationserver }}"
      - name: "fixes.apply"
        value: "ALL"
      - name: "is.key.license.alias"
        value: "*_PIE_10.*_*_*"
    cce_provisioning_template_params_secure:
      - name: "is.administrator.password"
        value: "{{ cce_provisioning_is_administrator_password }}"
  tags:
    - install
    - install-integrationserver